# FROM mcr.microsoft.com/dotnet/sdk
FROM mcr.microsoft.com/dotnet/sdk

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && \
    dotnet tool install ilspycmd -g
